### ISSUE TITLE
Umbrella 1.0

### ISSUE THREAD

**Issue by rofrischmann** [rofrischmann/fela#29]
This is a list of things that need to be done before releasing version 1.0 (first stable).
Fela actually is quite stable and produces correct, minimal and compressed markup. It is just very young (2 weeks~) and therefore not very matured.

(The list might be updated next days)

- [x] just **test** Fela in a real world application *(maybe by replacing react-look)*
- [x] complete docs ( https://github.com/rofrischmann/fela/issues/35 )
- [x] better/more examples ( https://github.com/rofrischmann/fela/issues/28 )
