### ISSUE TITLE
babel-plugin-fela

### ISSUE THREAD

**Issue by rofrischmann** [rofrischmann/fela#305]
**Environment**: Both
**Type**: Performance

This is the main issue for a Babel plugin.

-------------------

#### Description
First of all, **why a babel plugin?**
Using Babel we can transform our code during compilation, which can help to bring drastic performance optimizations for Fela. We may especially improve rule functions themselves.

#### ToDo
- [x] extract static properties to prerender once
- [x] transform `createComponent` first parameter
- [x] add renderer as second parameter if possible
- [x] safety checks to not break rules
- [x] enable precompiled styles
- [x] enable custom 2. parameter
- [x] build source with real AST nodes rather than source strings
- [x] proper static extraction helper based on AST nodes
- [x] enable static style extraction / cache rehydration
- [x] test fixtures

**Comment by mesteche** [comment]
Hello,
I have a few question about this babel-plugin:
- Is this plugin supposed to achieve something similar to the *Extract mode* of emotion (https://github.com/tkh44/emotion/blob/master/docs/extract-mode.md) ?
- Can we achieve the same thing with a babel-macro (https://github.com/kentcdodds/babel-macros) instead of a babel-plugin ?

About that last one, create-react-app could soon support babel-macro, so if this plugin was a macro it could be used in create-react-app without having to *eject* or fork.

Nice work on fela by the way.

**Comment by rofrischmann** [comment]
For now this plugin does **not** extract CSS files. I don't see any benefit of doing so. But ofc this plugin is start the beginning. We can do basically everything with it.
I did not check babel-macro's yet, might check that later, but for now I'll stick to the plugin I guess.

**Comment by mesteche** [comment]
About the benefits of extracting CSS files:
The browser can cache these files separately from the javascript and html.
Thanks to HTTP/2 it can even be "pushed" with the page without being directly included in `<style/ >` tags (so we keep the benefit of separated caches).
It can also start interpreting the css before the javascript kicks in.
For the components with static rules only (without props related values), I think the HoC can be completely removed and the class names can be defined statically which can improve performance.
The last two should also be possible without completely extracting the css in separate files.

**Comment by alanhogan** [comment]
The link above 404d, but here is a version that works: https://github.com/emotion-js/emotion/blob/b0c1427d3a8f689e637a7c4011c844292c704426/docs/extract-mode.md
